#!/bin/bash
#
#This script is about cleaning up log files based on retention policy
#
#Author: Dharmendra Gupta
#Date Created: 25th Sep 2025
#Version: 1.0.0
#
#Usage: ./cleanup_logs.sh

# Retention Period in days
Retention=10

# Directory containing log file
LOG_DIR="/tmp/test-logs"

# Extenstion
Extension="*.log"

# Logging
echo "[$(date)] Cleaning up logs in $LOG_DIR older than $Retention days..."

# Find and delete log files older than Retension days
find $LOG_DIR -type f -name $Extension -mtime +$Retention -print -exec rm -f {} \;


echo "[$(date)] cleanup complete."
